### ISSUE TITLE
No license found

### ISSUE THREAD

**Issue by JacksonChen666** [He3lixxx/five-words-five-letters#1]
This project does not seem to have a license declared in an obvious way, or at all. I recommend that a LICENSE file is added because this project seems be intended as open source, but is not open source without a license.

[What happens when there is no license?](https://choosealicense.com/no-permission/)

**Comment by richardebeling** [comment]
Resolved in [0248c6e](https://github.com/richardebeling/five-words-five-letters/commit/0248c6ed1d79230de7c6512e661cc2cdad687378)
